Update ptBR.ts
mui/mui-x pull request #12618
Opened 2024-03-30 06:48 UTC by hugoalkimim

Translate the remaining keys

- [X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

2024-04-02 13:30 UTC, JCQuintas approved these changes

2024-04-02 13:32 UTC, JCQuintas requested changes
Please make sure to run `yarn l10n` and commit the changes

2024-04-03 09:13 UTC, MBilalShafi approved these changes
Thank you for the contribution 👍

2024-04-03 09:16 UTC, JCQuintas approved these changes

2024-04-03 09:51 UTC, merged