[DataGrid] Add `getFilterState` method
mui/mui-x pull request #13418
Opened 2024-06-07 19:36 UTC by cherniavskii

2024-06-07 20:54 UTC, michelengelen approved these changes
Just a few nits! Looks pretty solid! :shipit:

2024-06-07 20:54 UTC, michelengelen commented on docs/data/data-grid/filtering-recipes/filtering-recipes.md
> +
Should we maybe add some description here?

2024-06-07 20:54 UTC, michelengelen commented on docs/data/data-grid/filtering-recipes/FilteredRowCount.tsx
> +  const [predefinedFiltersRowCount, setPredefinedFiltersRowCount] = React.useState<
I would probably prefer an object here, but I guess this is mainly personal preference. As long as the function is pure it should be fine.

2024-06-10 08:49 UTC, michelengelen requested changes
sry for the inconvenience! 🙇🏼

2024-06-10 08:49 UTC, michelengelen commented on docs/data/data-grid/filtering-recipes/filtering-recipes.md
> +{{"demo": "FilteredRowCount.js", "bg": "inline", "defaultCodeOpen": false}}
Hey @cherniavskii 
I am no allowed to push to your branch, so I'll just leave a suggestion here that you can apply

```suggestion

## Calculating row count in advance

In many data exploration scenarios, it's highly beneficial to display the row count associated with a predefined filter upfront.
This transparency empowers users to make informed decisions about which filter to apply, potentially saving them time and effort.

The [Grid API](/x/react-data-grid/api-object/#how-to-use-the-api-object) provides the [`getFilterState`](/x/api/data-grid/grid-api/#grid-api-prop-getFilterState) function, which allows you to retrieve the filter state for a given filter model without applying it to the data grid. By effectively utilizing `getFilterState`, you can dynamically calculate the row count that would result from applying a specific predefined filter.

{{"demo": "FilteredRowCount.js", "bg": "inline", "defaultCodeOpen": false}}
```

2024-06-10 22:00 UTC, romgrk commented on packages/x-data-grid/src/models/api/gridFilterApi.ts
> +  getFilterState: (filterModel: GridFilterModel) => GridStateCommunity['filter'];
This sounds like it should be a (pure) selector, but I see how that would be annoying to implement.

2024-06-10 22:00 UTC, romgrk approved these changes

2024-06-12 15:34 UTC, michelengelen commented on docs/data/data-grid/filtering-recipes/filtering-recipes.md
> +{{"demo": "FilteredRowCount.js", "bg": "inline", "defaultCodeOpen": false}}
@cherniavskii gentle ping 🔔

2024-06-13 10:17 UTC, cherniavskii commented
@michelengelen I need an approval from you in order to merge it

2024-06-13 10:23 UTC, merged