chore: fix typos
mui/mui-x pull request #13906
Opened 2024-07-19 18:23 UTC by cratiu222

Hello
I found some minor typos issues in your docs.
Br, Christina.

2024-07-19 19:00 UTC, oliviertassinari commented on docs/data/charts/axis/axis.md
>  Each axis definition is identified by its property `id`.
```suggestion
```

2024-07-19 19:03 UTC, oliviertassinari commented on docs/data/charts/axis/axis.md
```suggestion
```

2024-07-19 19:03 UTC, oliviertassinari commented on docs/data/charts/axis/axis.md
> +And series specifies the axis they use with `xAxisKey` and `yAxisKey` properties.
```suggestion
Then each series (in the `series` prop) specifies the axis they use with the `xAxisKey` and `yAxisKey` properties.
```

2024-07-19 19:06 UTC, oliviertassinari commented
I'm confused by the API. Why do we map yAxis `id` with `yAxisKey`:

```jsx
<LineChart
  xAxis={[{ data: sample }]}
  yAxis={[
    { id: 'linearAxis', scaleType: 'linear' },
    { id: 'logAxis', scaleType: 'log' },
  ]}
  series={[
    { yAxisKey: 'linearAxis', data: sample, label: 'linear' },
    { yAxisKey: 'logAxis', data: sample, label: 'log' },
  ]}
  leftAxis="linearAxis"
  rightAxis="logAxis"
  height={400}
/>
```

https://deploy-preview-13906--material-ui-x.netlify.app/x/react-charts/axis/#defining-axis

Why not:

```jsx
<LineChart
  xAxis={[{ data: sample }]}
  yAxis={[
    { id: 'linearAxis', scaleType: 'linear' },
    { id: 'logAxis', scaleType: 'log' },
  ]}
  series={[
    { yAxisId: 'linearAxis', data: sample, label: 'linear' },
    { yAxisId: 'logAxis', data: sample, label: 'log' },
  ]}
  leftAxisId="linearAxis"
  rightAxisId="logAxis"
  height={400}
/>
```

2024-07-22 06:13 UTC, arminmeh requested changes

2024-07-22 06:13 UTC, arminmeh commented on docs/data/data-grid/column-definition/column-definition.md
> +You can create the array outside the render function or memorize it.
This is not a typo
It refers to https://react.dev/reference/react/useMemo
> Caching return values like this is also known as [memoization,](https://en.wikipedia.org/wiki/Memoization) which is why this Hook is called useMemo

2024-07-24 08:49 UTC, JCQuintas approved these changes

2024-07-24 09:19 UTC, merged