[data grid] Add `Api` type param to cell params interfaces
mui/mui-x pull request #15968
Opened 2024-12-21 19:44 UTC by k-rajat19

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes https://github.com/mui/mui-x/issues/15963

2024-12-27 06:36 UTC, k-rajat19 commented
@michelengelen, can you review this? 
Side Note: I'm reexporting these types for pro and premium packages separately, one can pass pro and premium grid API in `Api` type param easily.

2024-12-27 11:10 UTC, michelengelen approved these changes
LGTM, but I would like a second review from @arminmeh about this.

2025-01-03 10:30 UTC, arminmeh commented
> Side Note: I'm not reexporting these types for pro and premium packages separately, one can pass pro and premium grid API in Api type param easily.

Is this expected from the users?

Looking backwards, I think that we shouldn't have done this
https://github.com/mui/mui-x/pull/14201 (related issue https://github.com/mui/mui-x/issues/14190)

This made `api` public API

We are not accessing `api` in any of our examples. People can use internal API, but that does not mean that we have to make it public.

@mui/xgrid should we remove `api` from the public API in v8 and just patch v7 to support proper types?

2025-01-03 21:49 UTC, cherniavskii commented
> This made api public API
> We are not accessing api in any of our examples. People can use internal API, but that does not mean that we have to make it public.

Not sure what you mean here. `api` in this case is the same as `apiRef.current`, isn't it?

2025-01-06 08:09 UTC, arminmeh commented
> api in this case is the same as apiRef.current, isn't it

true, but we added another public point of accessing it.
I didn't deep dive into the initial issue where it was requested to document this, but I feel that we didn't had to.
Then we would also not have this "problem". And the proposed solution is that the developers still have to do some additional work, so it is just creating unnecessary complexity IMO

2025-01-06 19:17 UTC, arminmeh commented
`api` was attached to the cell params because of https://github.com/mui/mui-x/blob/v7.23.5/packages/x-data-grid/src/components/cell/GridCell.tsx#L196
I don't think it was meant to be documented and part of the public API

2025-01-06 22:56 UTC, romgrk commented
I think we should be removing `api` from the public API. We also expose our API as `api` is other places, that we should also remove.

2025-03-25 13:23 UTC, michelengelen commented
comment for testing!

2025-05-14 20:51 UTC, arminmeh requested changes
>Side Note: I'm not reexporting these types for pro and premium packages separately, one can pass pro and premium grid API in Api type param easily.

This creates a burden for the developer and I think that needs to be addressed before merging

2025-06-29 03:35 UTC, closed without merging