[docs] add ignoreInvalidInputs js doc
mui/mui-x pull request #5735
Opened 2022-08-08 13:09 UTC by PavelKoroteev

2022-08-08 19:45 UTC, oliviertassinari commented on packages/x-date-pickers/src/DatePicker/DatePicker.tsx
> +   * Do not fire onChange for Invalid Date
Would it be better?

```suggestion
   * If true, do not fire onChange for an invalid date.
```

2022-08-09 06:56 UTC, LukasTy requested changes

2022-08-09 06:56 UTC, LukasTy commented on packages/x-date-pickers/src/DatePicker/DatePicker.tsx
> +  /**
Thank you for the contribution.
Proptypes in our project are generated as are their comments.
Could you please update the comment on this corresponding field in `PureDateInput`, run `yarn proptypes` and then commit the changes?

2023-11-20 09:02 UTC, flaviendelangle commented
Closing this one, the prop no longer exists

2023-11-20 09:02 UTC, closed without merging