[docs] Change default date from 4th of April to 21st of April for readability
mui/mui-x pull request #8089
Opened 2023-03-01 14:52 UTC by flaviendelangle

2023-03-01 21:02 UTC, LukasTy requested changes
This is a really great readability improvement! ❤️ 
As someone, who "can only read" ISO dates I appreciate it very much. 👏 
Superb docs feedback point.

2023-03-02 07:22 UTC, flaviendelangle commented on docs/data/date-pickers/base-concepts/ComponentFamilies.tsx
> +            defaultValue={[dayjs('2022-04-21'), dayjs('2022-04-10')]}
:facepalm: ok I was too fast on this one...

2023-03-02 07:23 UTC, flaviendelangle commented on docs/data/date-pickers/base-concepts/ComponentFamilies.tsx
> +            defaultValue={[dayjs('2022-04-21'), dayjs('2022-04-10')]}
I'll set `04-17` as the default date and `04-21` as the 2nd date on range components

2023-03-02 08:10 UTC, LukasTy approved these changes
Great work! 👏 
Very nice result and a few optional alignment improvements so that all the date and times are the same everywhere. 👍

2023-03-02 08:10 UTC, LukasTy commented on packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.test.tsx
> +      render(<DateCalendar defaultValue={dayjs('2022-04-21')} onChange={onChange} />);
If we are aligning everywhere, then maybe going with the following would be a bit more correct? 🤔 
```suggestion
      render(<DateCalendar defaultValue={dayjs('2022-04-17')} onChange={onChange} />);
```

2023-03-02 08:10 UTC, LukasTy commented on packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.test.tsx
> +          <DateCalendar defaultValue={dayjs.utc('2022-04-21')} onChange={onChange} />
```suggestion
          <DateCalendar defaultValue={dayjs.utc('2022-04-17')} onChange={onChange} />
```

2023-03-02 08:10 UTC, LukasTy commented on packages/x-date-pickers/src/AdapterDayjs/AdapterDayjs.test.tsx
> +      const initialValue: [any, any] = [dayjs.utc('2022-04-21'), dayjs.utc('2022-04-21')];
```suggestion
      const initialValue: [any, any] = [dayjs.utc('2022-04-17'), dayjs.utc('2022-04-21')];
```

2023-03-02 10:21 UTC, merged