[DataGrid] Auto-scroll when making range selection
mui/mui-x pull request #8661
Opened 2023-04-18 13:06 UTC by m4theushw

Closes #8591 

Demo: https://codesandbox.io/s/brave-joliot-898u33?file=/demo.tsx

2023-04-19 06:30 UTC, MBilalShafi reviewed
Thank you for the awesome work 🎉 The cell selection feature now seems really solid.

While playing around, I observed a couple of minor things:
1. During dragging, when the mouse goes outside the grid, the scrolling goes on but the selection range is not anymore growing (unless we bring the mouse back to a certain cell in the grid). Is this intended? (I observed the same with AgGrid, but do you think it's more usable if we keep on adding cells to selection with drag, even if the mouse goes outside the grid 🤔)
2. Again, with mouse dragging, if we go off grid and then stop clicking (mouse up), on going back to the grid, grid still detects as if it's dragging, is it possible to remove the dragging once the user does a mouse up (even outside the grid).

![cellSelection](https://user-images.githubusercontent.com/12609561/232985397-eb926ae6-96b0-4c96-bce1-06a2f35d855f.gif)

2023-06-26 13:21 UTC, cherniavskii requested changes

2023-06-26 13:21 UTC, cherniavskii commented on packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
> +      }
Wouldn't `startAutoScroll` be called too often, even if the cursor is far from the edge of the virtual scroller?

```suggestion
      if (hasEnteredSensitivityArea) {
        // Mouse has entered the sensitity area for the first time
        startAutoScroll();
      } else {
        // Mouse has left the sensitivity area while auto scroll is on
        stopAutoScroll();
      }
```

2023-06-26 13:21 UTC, cherniavskii commented on packages/grid/x-data-grid-premium/src/tests/cellSelection.DataGridPremium.test.tsx
> +  describe('Auto-scroll', () => {
Use `clock.withFakeTimers();` in this section instead of enabling fake timers for the whole file?

2023-06-26 13:21 UTC, cherniavskii commented on packages/grid/x-data-grid-premium/src/hooks/features/cellSelection/useGridCellSelection.ts
> +        apiRef.current.virtualScrollerRef?.current?.getBoundingClientRect();
Did you consider moving the `getBoundingClientRect` call outside of `setInterval`?
[`getBoundingClientRect` triggers forced reflow / layout](https://gist.github.com/paulirish/5d52fb081b3570c81e3a), so maybe we can avoid calling it too often assuming that virtual scroller size is constant during the scrolling?

2023-07-04 08:30 UTC, cherniavskii approved these changes

2023-07-04 18:22 UTC, MBilalShafi approved these changes
Looks clean 🎉

2023-07-05 22:31 UTC, merged